### ISSUE TITLE
Example needed for onion-architecture

### ISSUE THREAD

**Issue by mpszczolinski** [zakirullin/cognitive-load#7]
Hey,

I am myself advocate of onion architecture. 

You said:

> we gave it all up in favour of the good old dependency inversion principle

I'd like to see an example, as for me, doing onion architecture is mainly "**dependency inversion principle**" plus keeping DOMAIN, BUSINESS LOGIC (Use cases) and INFRASTRUCTURE in 3 different layers, glued together with "**dependency inversion principle**".

I'd love to see explanation how "favour of the good old dependency inversion principle" is different from "onion architecture" so I can better understand that section.

best regards,
Maciej

**Comment by zakirullin** [comment]
@mpszczolinski Hi there!

The onion architecture variation I know implies using layers like: domain model, domain services, application services, infrastructure. Which is already more than you said. 

> 3 different layers
For me, [Palermo](https://jeffreypalermo.com/2008/07/the-onion-architecture-part-1/) some other people onion architecture is about four+ different layers. 

The point is, we tend to understand these kind of things in our own way. Then we build on that understanding. Then we have to transfer this understanding to our colleagues. And this is hard.

People spend time arguing whether their code should be placed in application services layer or domain services layer. People start thinking in terms of horizontal layers.

If we spend time thinking about splitting our code into so many horizontal layers, we will not have much mental capacity left for more important things. Important things like vertical slices, isolation, cohesion and so on.

Layers of abstractions aren't cheap, we should not add them blindly just everywhere. 

If I need some truly infrastructure-independent business logic, no problem, I'll use DIP. But I won't split my logic into "domain" or "business logic" layers (for me it is kind of the same core layer), because it may confuse others. I won't name it "Onion Architecture". Because even between two of us there's a different understanding of this onion architecture. Whereas DIP turns out to be a much simpler and harder to misinterpret.

**Comment by zakirullin** [comment]
https://github.com/zakirullin/cognitive-load/commit/cb424e1804e2f9fb1854968f415cb3d423d50e79

**Comment by zakirullin** [comment]
https://github.com/zakirullin/cognitive-load/discussions/24
